### ISSUE TITLE
Error when try  to enable monitoring...

### ISSUE THREAD

**Issue by ethilesen** [IBM/monitor-custom-ml-engine-with-ai-openscale#9]
Hi, When I run the subscription.quality_monitoring.enable(threshold=0.7, min_records=10)
I get the following:
---------------------------------------------------------------------------
MissingValue                              Traceback (most recent call last)
<ipython-input-50-b488cb6b5564> in <module>()
----> 1 subscription.quality_monitoring.enable(threshold=0.7, min_records=10)

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/ibm_ai_openscale/base_classes/configuration/quality_monitoring.py in enable(self, threshold, min_records, **kwargs)
     43         asset_properties = self._subscription.get_details()['entity']['asset_properties']
     44 
---> 45         validate_asset_properties(asset_properties, ['problem_type', 'label_column', 'output_data_schema'])
     46 
     47         if threshold is None or min_records is None:

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/ibm_ai_openscale/utils/utils.py in validate_asset_properties(asset_properties, properties_list)
    324                 elif prop == 'feature_fields' or 'categorical_fields':
    325                     raise MissingValue(prop.replace('fields', 'columns'),
--> 326                                        reason='Subscription is missing required asset property. Missing parameter can be specified using subscription.update() method.')
    327                 elif prop == 'output_data_schema':
    328                     raise MissingValue(prop,

MissingValue: No "label_column" provided.
Reason: Subscription is missing required asset property. Missing parameter can be specified using subscription.update() method.

Any tips ?

**Comment by scottdangelo** [comment]
There was a breaking change introduced in the python SDK version 2.x
I am working on a fix for this.
If you'd like to try a workaround in the meantime, you can restart the kernel, and then import a pinned version after the cell ` 1.1 Installation and authentication`
```
!pip install ibm-ai-openscale==1.0.429 --no-cache | tail -n 1
```

I'm testing a fix that uses the current 2.x version, and I will push it up to github and close this bug when it is tested and ready.
